### ISSUE TITLE
Repel

### ISSUE THREAD

**Issue by Joris-van-der-Wel** [Periapsis/aphelion#25]
Repel as in subspace.

This is not that difficult to implement, most of the things needed to implement this are already present.

A config setting should be added that specifies how much a certain projectile pushes ships and other projectiles away (for the duration of the projectile). Other config settings (that are already implemented) can be used to make sure the velocity of the projectile is 0 and that it does not collide with anything.

**Comment by Joris-van-der-Wel** [comment]
First version of the repel is done:

```yaml
- selector: {weapon: classic-repel}
  projectile-speed: 0
  projectile-damage: 0
  projectile-angle-relative: false
  projectile-speed-relative: false
  projectile-offset-y: 0
  projectile-hit-ship: false
  projectile-hit-tile: false
  weapon-fire-delay: 60

  projectile-force-distance-ship: 600000
  projectile-force-velocity-ship: 10000
  projectile-force-distance-projectile: 1000000
  projectile-force-velocity-projectile: 10000
  projectile-expiration-ticks: 1
  projectile-expiration-explode: true
  projectile-expiration-animation: *EXPLOSION_REPEL
```

This only implements the push effect

The next step is to apply a maximum speed to projectiles & ships within a range.
